x-common-extra-hosts:
  &extra-hosts
  extra_hosts:
    - "db:10.111.7.191"

services:
  django:
    <<: *extra-hosts

  celery:
    <<: *extra-hosts

  geoserver:
    <<: *extra-hosts

  db:
    deploy:
      replicas: 0